import smtplib
from email.mime.text import MIMEText


SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587

SENDER_EMAIL = "abhishek290yadav@gmail.com"

# Paste your App Password here
APP_PASSWORD = "slby rpcl ctxi qtfv"


def send_alert_email(hostname, ip_address, old_status, new_status):

    subject = f"[InfraPulse Alert] {hostname} Status Changed"

    body = f"""
InfraPulse Monitoring Alert
This is DBA server

Server: {hostname}
IP Address: {ip_address}

Previous Status: {old_status}
Current Status: {new_status}

Please investigate immediately.

Generated by InfraPulse Enterprise Monitor.
"""

    msg = MIMEText(body)

    msg["Subject"] = subject
    msg["From"] = SENDER_EMAIL
    msg["To"] = SENDER_EMAIL

    try:

        server = smtplib.SMTP(
            SMTP_SERVER,
            SMTP_PORT
        )

        server.starttls()

        server.login(
            SENDER_EMAIL,
            APP_PASSWORD
        )

        server.sendmail(
            SENDER_EMAIL,
            SENDER_EMAIL,
            msg.as_string()
        )

        server.quit()

        print(
            f"Email Alert Sent for {hostname}"
        )

    except Exception as e:

        print(
            f"Email Error: {e}"
        )